/**
 * Autonomous Curiosity Architecture (ACA) Types
 *
 * Defines types for autonomous goal generation and frontier exploration.
 */

/**
 * Knowledge frontier - areas where knowledge is lacking
 */
export interface KnowledgeFrontier {
  id: string;
  category: 'unknown_concept' | 'incomplete_information' | 'outdated_knowledge' | 'unexplored_topic';
  description: string;
  relatedContext: string[];
  discoveredAt: string;
  importance: number; // 0-1 score
  explorationCost: number; // estimated effort
}

/**
 * Capability frontier - abilities that are missing or could be improved
 */
export interface CapabilityFrontier {
  id: string;
  category: 'missing_tool' | 'inefficient_process' | 'error_prone_task' | 'manual_workflow';
  description: string;
  currentLimitation: string;
  potentialImprovement: string;
  discoveredAt: string;
  impact: number; // 0-1 score of potential benefit
  feasibility: number; // 0-1 score of implementation difficulty
}

/**
 * Autonomous objective generated by the ACA system
 */
export interface AutonomousObjective {
  id: string;
  type: 'explore_knowledge' | 'develop_capability' | 'optimize_process' | 'learn_skill';
  title: string;
  description: string;
  motivation: string; // Why this objective was generated
  frontierId?: string; // Link to the frontier that triggered this
  priority: number; // 0-1 score
  estimatedDuration: number; // minutes
  prerequisites?: string[];
  createdAt: string;
  status: 'proposed' | 'scheduled' | 'in_progress' | 'completed' | 'abandoned';
  result?: ObjectiveResult;
}

/**
 * Result of completing an objective
 */
export interface ObjectiveResult {
  success: boolean;
  summary: string;
  newKnowledge?: string[];
  newCapabilities?: string[];
  artifactsCreated?: string[];
  completedAt: string;
  lessonsLearned?: string[];
}

/**
 * Curiosity state for a session
 */
export interface CuriosityState {
  sessionId: string;
  enabled: boolean;
  lastScanAt?: string;
  knowledgeFrontiers: KnowledgeFrontier[];
  capabilityFrontiers: CapabilityFrontier[];
  objectives: AutonomousObjective[];
  scanHistory: FrontierScan[];
  metrics: CuriosityMetrics;
}

/**
 * Record of a frontier scan
 */
export interface FrontierScan {
  timestamp: string;
  frontiersFound: number;
  objectivesGenerated: number;
  scanDuration: number; // milliseconds
  filesAnalyzed: string[];
}

/**
 * Metrics for curiosity-driven behavior
 */
export interface CuriosityMetrics {
  totalObjectivesGenerated: number;
  objectivesCompleted: number;
  objectivesAbandoned: number;
  totalExplorationTime: number; // minutes
  knowledgeGained: number; // count of new facts learned
  capabilitiesGained: number; // count of new skills/tools acquired
}

/**
 * Configuration for ACA scanner
 */
export interface ACAConfig {
  enabled: boolean;
  scanInterval: number; // minutes between scans
  maxGoalsPerCycle: number; // max objectives to generate per scan
  minImportanceThreshold: number; // 0-1, ignore frontiers below this
  autoScheduleObjectives: boolean; // automatically schedule high-priority objectives
  explorationBudget: number; // max minutes per day for autonomous exploration
}
